travis:
  secure:
    BINSTAR_TOKEN: kLGLyCZgLHvcTxm48mhB8lDVil4Qc6MgMt98OxDOJXzZBwHf0UgnqegY5/zvE6i2xMGvvRB94yA5IPxlWMD3g+VjGAogHxr3U76dIHs7OL3UMO9s8Kw6cqQNHrw/lBSaG3Wj++6eGgVdqgqdqVvF8tCTSxpK5iAd/+YqzoBLdomApM5w2Y78onufBCEo0RHxB1+ky8kwpmBS5KvCmzTX+GYSOpXUaNSevAGnJUiQSO6zJaJyZWzqUWlVfYeU2qjwgpq2i4oItr0+Cibs3uwtXU/j1eP17DMVk+NTjCJ3UZRV1tO1m0LBN4gOHy4yDY6BpHSiOYAqcF+gi7fU+obRdaixY2O+UltBZcXr9QHC4dt5yERCWCclYMifD1w5e1M4Sf8gj4K3JT+e1LAO3lcZZy4OO21BWd5xbzfjeBdblEetyr4to/BaNCoshwKbdgYpFrX2gM4QLSYvHtheLonr6YEu+nY+rsJR/q94KoYHt8ilF4zNUtokODGLOfoTznW6SxSt6sTjYU2ZCd8f0dqz3GgJm5K0pEsp+Jga8osI4u4+HTB3tUDnNlbQnMKGH4KdF3ZlfAqCyafX3IkVnQ0YSJ4BBdoYOS3uqWTIFBw04dm9JgAxqkB8OnjAzzCkWorUDWBMJsRbrl9n/H2e+xToGXZiWPlssFpN7y+Wxfdf5sQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
