travis:
  secure:
    BINSTAR_TOKEN: l5A5pka9EPjhhN9S8wVP7zyDJQ0qtl/T310SqLmxbFQQjF7xuPyYMAOSzGKu8Mq96Wj4b72ltv1EAfWvOChaDD8JPnzN7Dhyf5f32x+DxPo6xAASEmuOPnPHfCp/BeEC3rBq47KfY+GmOO0INC3t4uiWT/ntxyVVBgAAOwz6mkjz9iczME3QYynH6n32asRKcRVLMEcvuX9iKdR5JqkgNmsnps+dfLeGLK3SnJQB3anhUWd0bcA35wVKWLoDs5A8Ri6gUhzsQRsywwqy+vcJa9HQzDwEXtcFXOnCWXVo2GlezBJJN9J9qHcKVLPhi/bRAZbdBflPM+DIXwop63boiTzBrxd9RwmXDSnlCdcFtDeg7PiFfu2CNqGB0oJfEctGo6/F0kTXphSC6WdADRYXgZ1gH4ZKg7rb/xPh18PlqPHpKEL0PYBUmqsMdZcLLi32PugnLmuAbRFDz1z+h4bCSANgVS9g+MXENMW4UtWIcv96Gcl31CvvUOndFI0cYegCCiARgefcjDbTpCMtKOVvsvc+EY9sg3G/LowG+7l97+2T1/nZOJGdn/A9cXX0AFqplZ/5MNqQ8RiEeX248g9Gq87ix4K0i9Ilr8S9rahB5KSCS9vpgCJjNcMPnOdiDUWwRZibyNB0Owj63bb13zQUOQIMa8CHkGon/f5SxMUnSak=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
